GCC = g++
NVCC = /usr/local/cuda/bin/nvcc -ccbin $(GCC)
NVCCFLAGS = -m${OS_SIZE} ${ARCH_FLAGS} -Xcompiler -fPIC
NVCC_INC = -I/usr/lib64/R/include  \
	   -I/usr/local/cuda/include -I./Random123-1.08/include 
SHLIB_FLAGS = -L/usr/local/cuda/lib64  -lcudart 
 
idealcu:
	$(NVCC) $(NVCFLAGS) $(NVCC_INC) --compiler-options -fPIC -c ideal.cu
	R CMD SHLIB $(SHLIB_FLAGS) ideal.o -o idealcu.so

clean:
	find . -name *~ -type f -delete	
	- rm *.o

clean_so:
	rm *.so

